// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.3
// source: dandelion/letters/letters.proto

package letters

import (
	core "github.com/chronos-tachyon/dandelion/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstablishLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed      []byte          `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Addresses []*core.Address `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *EstablishLink) Reset() {
	*x = EstablishLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dandelion_letters_letters_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstablishLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstablishLink) ProtoMessage() {}

func (x *EstablishLink) ProtoReflect() protoreflect.Message {
	mi := &file_dandelion_letters_letters_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstablishLink.ProtoReflect.Descriptor instead.
func (*EstablishLink) Descriptor() ([]byte, []int) {
	return file_dandelion_letters_letters_proto_rawDescGZIP(), []int{0}
}

func (x *EstablishLink) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *EstablishLink) GetAddresses() []*core.Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type RetireLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RetireLink) Reset() {
	*x = RetireLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dandelion_letters_letters_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetireLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetireLink) ProtoMessage() {}

func (x *RetireLink) ProtoReflect() protoreflect.Message {
	mi := &file_dandelion_letters_letters_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetireLink.ProtoReflect.Descriptor instead.
func (*RetireLink) Descriptor() ([]byte, []int) {
	return file_dandelion_letters_letters_proto_rawDescGZIP(), []int{1}
}

type ForwardEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Envelope *core.SealedEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
}

func (x *ForwardEnvelope) Reset() {
	*x = ForwardEnvelope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dandelion_letters_letters_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForwardEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardEnvelope) ProtoMessage() {}

func (x *ForwardEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_dandelion_letters_letters_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardEnvelope.ProtoReflect.Descriptor instead.
func (*ForwardEnvelope) Descriptor() ([]byte, []int) {
	return file_dandelion_letters_letters_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardEnvelope) GetEnvelope() *core.SealedEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

var File_dandelion_letters_letters_proto protoreflect.FileDescriptor

var file_dandelion_letters_letters_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x64, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x69, 0x6f, 0x6e, 0x2f, 0x6c, 0x65, 0x74, 0x74,
	0x65, 0x72, 0x73, 0x2f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x64, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x69, 0x6f, 0x6e, 0x2e, 0x6c, 0x65, 0x74,
	0x74, 0x65, 0x72, 0x73, 0x1a, 0x14, 0x64, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x69, 0x6f, 0x6e, 0x2f,
	0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x0d, 0x45, 0x73,
	0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12,
	0x30, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x69, 0x6f, 0x6e, 0x2e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x69, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x22,
	0x48, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x64, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x69, 0x6f, 0x6e,
	0x2e, 0x53, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x52,
	0x08, 0x65, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x6f, 0x73, 0x2d,
	0x74, 0x61, 0x63, 0x68, 0x79, 0x6f, 0x6e, 0x2f, 0x64, 0x61, 0x6e, 0x64, 0x65, 0x6c, 0x69, 0x6f,
	0x6e, 0x2f, 0x6c, 0x65, 0x74, 0x74, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dandelion_letters_letters_proto_rawDescOnce sync.Once
	file_dandelion_letters_letters_proto_rawDescData = file_dandelion_letters_letters_proto_rawDesc
)

func file_dandelion_letters_letters_proto_rawDescGZIP() []byte {
	file_dandelion_letters_letters_proto_rawDescOnce.Do(func() {
		file_dandelion_letters_letters_proto_rawDescData = protoimpl.X.CompressGZIP(file_dandelion_letters_letters_proto_rawDescData)
	})
	return file_dandelion_letters_letters_proto_rawDescData
}

var file_dandelion_letters_letters_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dandelion_letters_letters_proto_goTypes = []interface{}{
	(*EstablishLink)(nil),       // 0: dandelion.letters.EstablishLink
	(*RetireLink)(nil),          // 1: dandelion.letters.RetireLink
	(*ForwardEnvelope)(nil),     // 2: dandelion.letters.ForwardEnvelope
	(*core.Address)(nil),        // 3: dandelion.Address
	(*core.SealedEnvelope)(nil), // 4: dandelion.SealedEnvelope
}
var file_dandelion_letters_letters_proto_depIdxs = []int32{
	3, // 0: dandelion.letters.EstablishLink.addresses:type_name -> dandelion.Address
	4, // 1: dandelion.letters.ForwardEnvelope.envelope:type_name -> dandelion.SealedEnvelope
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dandelion_letters_letters_proto_init() }
func file_dandelion_letters_letters_proto_init() {
	if File_dandelion_letters_letters_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dandelion_letters_letters_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstablishLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dandelion_letters_letters_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetireLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dandelion_letters_letters_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForwardEnvelope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dandelion_letters_letters_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dandelion_letters_letters_proto_goTypes,
		DependencyIndexes: file_dandelion_letters_letters_proto_depIdxs,
		MessageInfos:      file_dandelion_letters_letters_proto_msgTypes,
	}.Build()
	File_dandelion_letters_letters_proto = out.File
	file_dandelion_letters_letters_proto_rawDesc = nil
	file_dandelion_letters_letters_proto_goTypes = nil
	file_dandelion_letters_letters_proto_depIdxs = nil
}
